### ISSUE TITLE
Not working on 1.19.3

### ISSUE THREAD

**Issue by SpiritOTHawk** [shedaniel/advancements-enlarger#13]

**Comment by ArmouryGaming** [comment]
Would also appreciate this being updated to 19.3. Minecraft crashes to desktop when the Advancement screen opens with the current 19.2 version.

**Comment by Xrey274** [comment]
I just opened a pull request for the update. You can use my fork for 1.19.3 until it's merged.

**Comment by shedaniel** [comment]
A 1.19.3 version has been released now! Thank you for being patient.
