### ISSUE TITLE
1.19 version crashes when trying to view the advancements tab

### ISSUE THREAD

**Issue by EmpressAutumn** [shedaniel/advancements-enlarger#9]
The mod's most current 1.19 release crashes the game when I attempt to view the advancements screen.

**Comment by EmpressAutumn** [comment]
Shoot I guess I should include the crash report: [https://pastebin.com/bDiB9YEN](https://pastebin.com/bDiB9YEN)

**Comment by crest1993** [comment]
+1
[crash-2022-06-25_04.26.51-client.txt](https://github.com/shedaniel/advancements-enlarger/files/8981581/crash-2022-06-25_04.26.51-client.txt)

**Comment by ryanscarr** [comment]
> +1 [crash-2022-06-25_04.26.51-client.txt](https://github.com/shedaniel/advancements-enlarger/files/8981581/crash-2022-06-25_04.26.51-client.txt)

ok, mlengka93@gmail.com.
PSA to remember to remove sensitive info from your crash reports.

**Comment by maxvar** [comment]
added PR for changes to support 1.19 (https://github.com/shedaniel/advancements-enlarger/pull/10)

**Comment by DanMeadWasTaken** [comment]
Still seems to be an issue :D 
https://crashy.net/2DrCNYJEI1jCCE5FxfT2

**Comment by DanMeadWasTaken** [comment]
I tried finding the mod causing the issue, but even with the bare minimum of just some mods to speed up the game and better combat + 1-2 cosmetic mods, it's still crashing. 
https://paste.ee/p/Ecygi

**Comment by maxvar** [comment]
> I tried finding the mod causing the issue, but even with the bare minimum of just some mods to speed up the game and better combat + 1-2 cosmetic mods, it's still crashing. https://paste.ee/p/Ecygi

From what I see from the log you still try to use the old version. You can try to build from https://github.com/shedaniel/advancements-enlarger/commit/22e2ed64c6b6802e3cce739099228b5d35150509 and check if the updated version works.

**Comment by DanMeadWasTaken** [comment]
![image](https://user-images.githubusercontent.com/75497984/187094344-58476609-ad51-426a-99e1-5b25c5c11d8c.png)
So, I downloaded it, ad tried building it after downloading gradle but got this error
according to the build scan, no errors occurred yet when I try to look for the completed file, It's nowhere to be found. What may i have done wrong? https://scans.gradle.com/s/dp2ocloiho4mw

**Comment by maxvar** [comment]
just `gradle assemble` and get mod jar from `build/libs`

**Comment by DanMeadWasTaken** [comment]
alright, so that worked, and this version doesn't crash! Thaks, I was using gradle build instead of gradle assemble
